base_url = "https://adavidwilson.com"
compile_sass = true
build_search_index = true
theme = "after-dark"
taxonomies = [
  {name = "categories", feed = true},
  {name = "tags", feed = true},
]

[markdown]
highlight_code = true

[extra]
after_dark_menu = [
  {url = "$BASE_URL", name = "Home"},
  {url = "$BASE_URL/categories", name = "Categories"},
  {url = "$BASE_URL/tags", name = "Tags"},
  {url = "https://www.linkedin.com/in/anotherdavidwilson/", name = "LinkedIn"},
]
after_dark_title = "David Wilson | Developer, Teacher, Tinkerer"
