baseURL: https://www.adavidwilson.com
languageCode: en-us
title: "David's Portfolio"

module:
  imports:
  - path: github.com/hugo-toha/toha/v4
  mounts:
  - source: static
    target: static
  - source: static/files
    target: static/files
  - source: ./node_modules/flag-icon-css/flags
    target: static/flags
  - source: ./node_modules/@fontsource/mulish/files
    target: static/files
  - source: ./node-modules/katex/dist/fonts
    target: static/fonts

languages:
  en:
    languageName: English
    weight: 1

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

outputs:
  home:
    - HTML
    - RSS
    - JSON

enableEmoji: true

params:
  background: /images/site/background.jpg

  logo:
    main: /images/site/main-logo.png
    inverted: /images/site/inverted-logo.png
    favicon: /images/site/favicon_white/android-chrome-192x192.png

  gitRepo: https://github.com/adavidwilson/adavidwilson.github.io
  gitBranch: main

  topNavbar:
    maxVisibleSections: 5

  features:
    darkMode:
      enable: true

  footer:
    enable: true
    template: footer.html
    navigation:
      enable: true
      customMenus: true
    contactMe:
      enable: true
    credentials:
      enable: true

    newsletter:
      enable: false

    disclaimer:
      enable: false
